name = "rsw"
version = "0.1.0"

#! time interval for file changes to trigger wasm-pack build, default `50` milliseconds
interval = 50

cli = "npm"

[new]
using = "wasm-pack"

[[crates]]
name = "plot"
link = true